// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq3I0DJPf-81vQeTB4708KwF2MJPs-ZUg',
    appId: '1:1068250601822:web:3cc62a003581fc53cdd7cf',
    messagingSenderId: '1068250601822',
    projectId: 'samvargani',
    authDomain: 'samvargani.firebaseapp.com',
    databaseURL: 'https://samvargani-default-rtdb.firebaseio.com',
    storageBucket: 'samvargani.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk9hoLTqZUzoc1GfDGgvv4ia_XP6TM30o',
    appId: '1:1068250601822:android:c2772fbad5fad5efcdd7cf',
    messagingSenderId: '1068250601822',
    projectId: 'samvargani',
    databaseURL: 'https://samvargani-default-rtdb.firebaseio.com',
    storageBucket: 'samvargani.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQdydoLmdEZmTJ81Xv8Wb8EUhyvyO5zBk',
    appId: '1:1068250601822:ios:934d11720864dba7cdd7cf',
    messagingSenderId: '1068250601822',
    projectId: 'samvargani',
    databaseURL: 'https://samvargani-default-rtdb.firebaseio.com',
    storageBucket: 'samvargani.appspot.com',
    iosClientId: '1068250601822-4n09gdhbvf46hrnnjlubi1pak8uet798.apps.googleusercontent.com',
    iosBundleId: 'com.aruhant.paheli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQdydoLmdEZmTJ81Xv8Wb8EUhyvyO5zBk',
    appId: '1:1068250601822:ios:d99c40865eab6618cdd7cf',
    messagingSenderId: '1068250601822',
    projectId: 'samvargani',
    databaseURL: 'https://samvargani-default-rtdb.firebaseio.com',
    storageBucket: 'samvargani.appspot.com',
    iosClientId: '1068250601822-1jt41ene7qmv3hnjtfjq7hjus1rt4ks3.apps.googleusercontent.com',
    iosBundleId: 'com.aruhant.paheli.RunnerTests',
  );
}
